PREFIX    = /usr
MANPREFIX = $(PREFIX)/share/man

CC = c99

HAVE_GRAPHEME         = yes
GRAPHEME_CPPFLAGS_yes = -DHAVE_GRAPHEME
GRAPHEME_LDFLAGS_yes  = -lgrapheme

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE $(GRAPHEME_CPPFLAGS_$(HAVE_GRAPHEME))
CFLAGS   = -Wall -g
LDFLAGS  = $(GRAPHEME_LDFLAGS_$(HAVE_GRAPHEME))
